feat: 二次开发接口-多媒体
linuxdeepin/dtkmultimedia pull request #1
Opened 2022-10-18 09:33 UTC by myk1343

二次开发接口-多媒体

Log: 二次开发接口-多媒体

2022-10-19 02:27 UTC, BLumia requested changes

2022-10-19 02:27 UTC, BLumia commented on CMakeLists.txt
> +project(${BIN_NAME})
不建议去掉 DTK 模板里的这个版本号相关的部分，CI 传递版本号带后缀的问题可以参考 dtkcore 的处理方式： https://github.com/linuxdeepin/dtkcore/blob/9371813c93d5660a98b62051f6e66f96ee3c3bcb/debian/rules#L10

2022-10-19 02:34 UTC, wineee commented on CMakeLists.txt
> +project(${BIN_NAME})
此外dtkcore是 -DDVERSION=$(PACK_VER)，这里原来的写法是 -DVERSION=$(PACK_VER)
使用 VERSION 还是 DVERSION，dtk 组件应该统一一下

2022-10-19 03:32 UTC, BLumia commented on debian/control
>   .
描述

2022-10-19 05:09 UTC, wineee commented on debian/rules
> +	dh_auto_configure -- -DBUILD_VERSION=$(BUILD_VER) -DDVERSION=$(PACK_VER)
你用的 VERSION 这应该是 -DVERSION=$(PACK_VER)，不是 -DDVERSION

2022-10-20 05:12 UTC, itsXuSt commented
对外公开接口应放在 ./include 目录下。

2022-10-20 05:15 UTC, itsXuSt commented
commit message 用英文。

2022-10-20 05:16 UTC, itsXuSt requested changes
docs 文件夹不是 doc

2022-10-20 05:17 UTC, toberyan reviewed
注释了多个需要修改的地方，另外为啥会有一张jpg图片？（mediaplayrex.jpg）

2022-10-20 05:17 UTC, toberyan commented on src/common/algorithm/demo.cpp
> +
这个文件全部都注释掉了，是用来干嘛的？

2022-10-20 05:17 UTC, toberyan commented on src/common/utils/hwdec_probe.cpp
> + *
这个开源协议头部缝合了，有点奇怪

2022-10-20 05:17 UTC, toberyan commented on src/common/utils/options.h
> + * modify it under the terms of the GNU General Public License as
这个开源协议头部缝合了，有点奇怪

2022-10-20 05:17 UTC, toberyan commented on src/engine/multimedia/player/filefilter.h
> + */
注释没有按照二次开发接口规范来做

2022-10-20 05:21 UTC, Johnson-zs requested changes

2022-10-20 05:21 UTC, Johnson-zs commented on examples/player/player.pro
> +TEMPLATE = app
为啥会有pro工程的文件

2022-10-20 05:39 UTC, itsXuSt requested changes

2022-10-20 05:39 UTC, itsXuSt commented on debian/control
> + qtbase5-dev, pkg-config, qttools5-dev-tools,
建议一行一个依赖

2022-10-20 05:39 UTC, itsXuSt commented on examples/player/doc/src/player.qdoc
> +/****************************************************************************
所有文件的版权声明应该使用 reuse

2022-10-20 05:39 UTC, itsXuSt commented on examples/player/player.h
> +    DMediaPlayer *m_player = nullptr;
不对外暴露的信息建议使用私有类封装。

2022-10-20 05:39 UTC, itsXuSt commented on src/common/utils/hwdec_probe.cpp
> +
建议使用 clang-format 对代码格式进行整理。

2022-10-20 05:39 UTC, itsXuSt commented on src/common/utils/hwdec_probe.h
> +        static HwdecProbe             m_ffmpegProbe;
指针没有初始值

2022-10-20 05:39 UTC, itsXuSt commented on src/common/utils/options.cpp
> +        _instance = new CommandLineManager();
单例如何释放？命名不规范。

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/interface/compositing_manager.h
> +    INTEROP_NONE,
枚举不使用下划线命名法

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/interface/compositing_manager.h
> +    bool _composited {false};
同类成员命名规范应一致

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/multimedia/daudioout.h
> +#ifndef DAudioOutput_H
guard 应全大写，endif 后应添加注释 // DAUDIOOUTPUT_H

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/multimedia/dplatformmediaplayer.h
> +    virtual qint64 duration() const = 0;
应合理使用空行

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/multimedia/dplatformmediaplayer.h
> +    void durationChanged(qint64 duration) {
头文件内短函数实现建议加 inline

2022-10-20 05:39 UTC, itsXuSt commented on src/engine/multimedia/dvideosink.cpp
> +#include <qvariant.h>
Qt 头文件应用应尽量使用 QAbcde 而不是 qabcde.h

2022-10-20 07:40 UTC, BLumia commented on examples/player/doc/src/player.qdoc
> +/****************************************************************************
目前的 doxygen 配置应该不支持 qdoc 文档，qdoc 和 doxygen 的语法格式也有差异，这点也需要留意

2022-10-25 13:09 UTC, closed without merging