feat: 单元测试
linuxdeepin/dtkmultimedia pull request #4
Opened 2022-11-01 13:42 UTC by myk1343

单元测试

Log: dengineplayer-单元测试

2022-11-02 02:02 UTC, itsXuSt commented
单元测试提交 Tag 应为 test: 而不是 feat:

2022-11-02 02:02 UTC, itsXuSt commented
commit message 应写英文

2022-11-02 02:05 UTC, itsXuSt requested changes
如评论，请修改

2022-11-02 02:15 UTC, myk1343 commented
> 如评论，请修改

已修改

2022-11-02 02:18 UTC, itsXuSt requested changes

2022-11-02 02:18 UTC, itsXuSt commented on include/dtkmultimediawidgets/dengineplayer.h
> +    PlayMode playMode();
getter 成员函数应当标注 const

2022-11-02 02:18 UTC, itsXuSt commented on include/dtkmultimediawidgets/dengineplayer.h
>      PlayerEngine *m_engine;
指针应初始化

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
> +    return nullptr;
未完全实现的函数应正确标注 TODO

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
> +        return (PlayMode)(m_engine->playlist().playMode());
尽可能的使用 c++ 的 cast

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
>      }
分支缺少返回值

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
> +        return m_engine->addPlayFile(url);
分支缺少返回值

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
> +        memcpy(&m_movieInfo, &(engine->movieInfo()), sizeof (MovieInfo));
建议复制构造函数赋值

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/dengineplayer.h
> +    PlayMode playMode();
该头文件与 include 目录头文件似乎是一样的？

2022-11-02 02:18 UTC, itsXuSt commented on src/multimediawidgets/engine/multimedia/player/dplaylistmodel.cpp
>      Q_ASSERT(m_infos.size() > 0);
这里有必要 assert 么？

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-denginegstplayer.cpp
> +// SPDX-FileCopyrightText: 2022 UnionTech Software Technology Co., Ltd.
单元测试文件名一般使用 _ 而不是 - 分隔。
参见 dtk-mount 及 dtksystemsettings

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-denginegstplayer.cpp
> +        m_player = new DMediaPlayer(NULL);
使用 nullptr 而不是 NULL

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-denginegstplayer.cpp
> +        delete m_videoWgt;
4个 new 但是 3 个 delete

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-denginegstplayer.cpp
> +    m_enginePlayer->setVideoSink(nullptr);
缺少检查点

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-denginegstplayer.cpp
> +     m_enginePlayer->playByName(QUrl("test"));
缩进不正确，请使用 clang-format 进行代码格式化，下同。

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-dengineplayer.cpp
> +#include "mockdemo/mockdemo.h"
头文件引入顺序不正确

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-dengineplayer.cpp
> +//        delete m_enginePlayer;
4 个 new 3 个 delete

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-dengineplayer.cpp
> +    m_enginePlayer->setVideoSink(nullptr);
缺失检查点

2022-11-02 02:18 UTC, itsXuSt commented on tests/ut-dengineplayer.cpp
> +     m_enginePlayer->setVideoRotation(90);
代码缩进，使用 clang-format

2022-11-02 02:19 UTC, itsXuSt commented
> > 如评论，请修改
> 
> 已修改

不是修改 pr message 而是 commit message。
pr message 不会出现在 git repo 中。

2022-11-02 02:37 UTC, itsXuSt commented
> > > 如评论，请修改
> > 
> > 
> > 已修改
> 
> 不是修改 pr message 而是 commit message。 pr message 不会出现在 git repo 中。

本地仓库 git rebase -i 或者 git commit --amend 修改 commit message 后用 git push -f 推送到自己的 fork 分支，pr 内的提交信息会自动更新。

2022-11-02 02:55 UTC, myk1343 commented on src/multimediawidgets/engine/multimedia/dengineplayer.cpp
> +        memcpy(&m_movieInfo, &(engine->movieInfo()), sizeof (MovieInfo));
两结构不一致，但是大小一致。

2022-11-02 07:55 UTC, myk1343 commented
> > > > 如评论，请修改
> > > 
> > > 
> > > 已修改
> > 
> > 
> > 不是修改 pr message 而是 commit message。 pr message 不会出现在 git repo 中。
> 
> 本地仓库 git rebase -i 或者 git commit --amend 修改 commit message 后用 git push -f 推送到自己的 fork 分支，pr 内的提交信息会自动更新。

review已修改，git commit --amend 这个需要改为git commit -a --amend

2022-11-03 01:04 UTC, uniontechzhangsong commented
+1

2022-11-03 01:33 UTC, toberyan approved these changes
+1

2022-11-03 01:55 UTC, myk1343 commented
/merge

2022-11-03 01:56 UTC, merged